#!/usr/bin/env python3

import os, sys, shutil

if __name__ == '__main__':
    fileslist = ['backend.py', 'copyright', 'mythbuntu-control-panel', 'plg_development.py', 'plg_system_roles.py', 'tab_plugins.ui',
    'dictionaries.py', 'mythbuntu_control_panel-0.0.0.egg-info', 'plg_mysql_config.py', 'plugin.py', 'tab_repos.ui',
    'changelog.gz', '__init__.py', 'mythbuntu-control-panel.1.gz', 'plg_plugins.py', 'README', 'tab_setup.ui',
    'com.mythbuntu.ControlPanel.conf', 'mythbuntu-control-panel.desktop', 'plg_repos.py', 'repos.db', 'tab_startup_behavior.ui',
    'com.mythbuntu.controlpanel.policy', 'mcp-backend', 'mythbuntu_control_panel.ui', 'plg_setup.py', 'tab_development.ui', 'tab_system_roles.ui',
    'com.mythbuntu.ControlPanel.service', 'mysql.py', 'mythbuntu.png', 'plg_startup_behavior.py', 'tab_mysql_config.ui']
    if os.geteuid() == 0:
        print('Checking if installation files are present')
        for file in fileslist:
            if not os.path.isfile('/tmp/' + file):
                print('One or more installation files could not be found')
                print('No changes made')
                print('Exiting')
                sys.exit(0)
        print('Changing each file owner and group id')
        for file in fileslist:
            shutil.chown('/tmp/' + file, 'root', 'root')
        print('Installing Mythbuntu Control Panel')
        shutil.move("/tmp/com.mythbuntu.ControlPanel.conf", "/etc/dbus-1/system.d/com.mythbuntu.ControlPanel.conf")
        shutil.move("/tmp/mythbuntu-control-panel", "/usr/bin/mythbuntu-control-panel")
        shutil.move("/tmp/mythbuntu_control_panel-0.0.0.egg-info", "/usr/lib/python3/dist-packages/mythbuntu_control_panel-0.0.0.egg-info")
        if not os.path.exists('/usr/lib/python3/dist-packages/MythbuntuControlPanel'):
            os.makedirs('/usr/lib/python3/dist-packages/MythbuntuControlPanel')
        shutil.move("/tmp/__init__.py", "/usr/lib/python3/dist-packages/MythbuntuControlPanel/__init__.py")
        shutil.move("/tmp/backend.py", "/usr/lib/python3/dist-packages/MythbuntuControlPanel/backend.py")
        shutil.move("/tmp/plugin.py", "/usr/lib/python3/dist-packages/MythbuntuControlPanel/plugin.py")
        shutil.move("/tmp/dictionaries.py", "/usr/lib/python3/dist-packages/MythbuntuControlPanel/dictionaries.py")
        shutil.move("/tmp/mysql.py", "/usr/lib/python3/dist-packages/MythbuntuControlPanel/mysql.py")
        shutil.move("/tmp/mythbuntu-control-panel.desktop", "/usr/share/applications/mythbuntu-control-panel.desktop")
        shutil.move("/tmp/com.mythbuntu.ControlPanel.service", "/usr/share/dbus-1/system-services/com.mythbuntu.ControlPanel.service")
        if not os.path.exists('/usr/share/doc/mythbuntu-control-panel'):
            os.makedirs('/usr/share/doc/mythbuntu-control-panel')
        shutil.move("/tmp/changelog.gz", "/usr/share/doc/mythbuntu-control-panel/changelog.gz")
        shutil.move("/tmp/copyright", "/usr/share/doc/mythbuntu-control-panel/copyright")
        shutil.move("/tmp/mythbuntu-control-panel.1.gz", "/usr/share/man/man1/mythbuntu-control-panel.1.gz")
        if not os.path.exists('/usr/share/mythbuntu'):
            os.makedirs('/usr/share/mythbuntu')
        shutil.move("/tmp/repos.db", "/usr/share/mythbuntu/repos.db")
        shutil.move("/tmp/mcp-backend", "/usr/share/mythbuntu/mcp-backend")
        if not os.path.exists('/usr/share/mythbuntu/ui'):
            os.makedirs('/usr/share/mythbuntu/ui')
        shutil.move("/tmp/mythbuntu_control_panel.ui", "/usr/share/mythbuntu/ui/mythbuntu_control_panel.ui")
        shutil.move("/tmp/mythbuntu.png", "/usr/share/pixmaps/mythbuntu.png")
        shutil.move("/tmp/com.mythbuntu.controlpanel.policy", "/usr/share/polkit-1/actions/com.mythbuntu.controlpanel.policy")
        if not os.path.exists('/usr/share/mythbuntu/plugins'):
            os.makedirs('/usr/share/mythbuntu/plugins')
        if not os.path.exists('/usr/share/mythbuntu/plugins/python'):
            os.makedirs('/usr/share/mythbuntu/plugins/python')
        shutil.move("/tmp/plg_startup_behavior.py", "/usr/share/mythbuntu/plugins/python/plg_startup_behavior.py")
        if not os.path.exists('/usr/share/mythbuntu/plugins/ui'):
            os.makedirs('/usr/share/mythbuntu/plugins/ui')
        shutil.move("/tmp/tab_startup_behavior.ui", "/usr/share/mythbuntu/plugins/ui/tab_startup_behavior.ui")
        shutil.move("/tmp/plg_system_roles.py", "/usr/share/mythbuntu/plugins/python/plg_system_roles.py")
        shutil.move("/tmp/tab_system_roles.ui", "/usr/share/mythbuntu/plugins/ui/tab_system_roles.ui")
        shutil.move("/tmp/plg_repos.py", "/usr/share/mythbuntu/plugins/python/plg_repos.py")
        shutil.move("/tmp/tab_repos.ui", "/usr/share/mythbuntu/plugins/ui/tab_repos.ui")
        shutil.move("/tmp/plg_mysql_config.py", "/usr/share/mythbuntu/plg_mysql_config.py")
        shutil.move("/tmp/tab_mysql_config.ui", "/usr/share/mythbuntu/tab_mysql_config.ui")
        shutil.move("/tmp/plg_plugins.py", "/usr/share/mythbuntu/plg_plugins.py")
        shutil.move("/tmp/tab_plugins.ui", "/usr/share/mythbuntu/tab_plugins.ui")
        shutil.move("/tmp/plg_setup.py", "/usr/share/mythbuntu/plugins/python/plg_setup.py")
        shutil.move("/tmp/tab_setup.ui", "/usr/share/mythbuntu/plugins/ui/tab_setup.ui")
        shutil.move("/tmp/plg_development.py", "/usr/share/mythbuntu/plugins/python/plg_development.py")
        shutil.move("/tmp/tab_development.ui", "/usr/share/mythbuntu/plugins/ui/tab_development.ui")
        print('Mythbuntu Control Panel was successfully installed.')
    else:
        print('This install script must be run with sudo')
        print('No changes made')
        print('Exiting')
